// Code generated by MockGen. DO NOT EDIT.
// Source: internal/cache/cache.go
//
// Generated by this command:
//
//	mockgen -source=internal/cache/cache.go -destination=mocks/cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
