// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/constants.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/constants.go -destination=mocks/constants.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
