// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/errors.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/errors.go -destination=mocks/errors.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
