// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	repository "github.com/flew1x/url_shortener_ms/internal/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockIRepository is a mock of IRepository interface.
type MockIRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRepositoryMockRecorder
}

// MockIRepositoryMockRecorder is the mock recorder for MockIRepository.
type MockIRepositoryMockRecorder struct {
	mock *MockIRepository
}

// NewMockIRepository creates a new mock instance.
func NewMockIRepository(ctrl *gomock.Controller) *MockIRepository {
	mock := &MockIRepository{ctrl: ctrl}
	mock.recorder = &MockIRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRepository) EXPECT() *MockIRepositoryMockRecorder {
	return m.recorder
}

// GetUrlRepository mocks base method.
func (m *MockIRepository) GetUrlRepository() repository.IURLRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUrlRepository")
	ret0, _ := ret[0].(repository.IURLRepository)
	return ret0
}

// GetUrlRepository indicates an expected call of GetUrlRepository.
func (mr *MockIRepositoryMockRecorder) GetUrlRepository() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUrlRepository", reflect.TypeOf((*MockIRepository)(nil).GetUrlRepository))
}
